// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for posts documents */
interface PostsDocumentData {
    /**
     * title field in *posts*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: posts.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * subtitle field in *posts*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: posts.subtitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    subtitle: prismicT.RichTextField;
    /**
     * author field in *posts*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: posts.author
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    author: prismicT.RichTextField;
    /**
     * banner field in *posts*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: posts.banner
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    banner: prismicT.ImageField<never>;
    /**
     * content field in *posts*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: posts.group[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    group: prismicT.GroupField<Simplify<PostsDocumentDataGroupItem>>;
}
/**
 * Item in posts → content
 *
 */
export interface PostsDocumentDataGroupItem {
    /**
     * heading field in *posts → content*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: posts.group[].heading
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    heading: prismicT.RichTextField;
    /**
     * body field in *posts → content*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: posts.group[].body
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    body: prismicT.RichTextField;
}
/**
 * posts document from Prismic
 *
 * - **API ID**: `posts`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PostsDocumentData>, "posts", Lang>;
export type AllDocumentTypes = PostsDocument;
/**
 * Primary content in SliceSpaceTravelling → Primary
 *
 */
interface SliceSpaceTravellingSliceDefaultPrimary {
    /**
     * Title field in *SliceSpaceTravelling → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: slice_space_travelling.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *SliceSpaceTravelling → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: slice_space_travelling.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for SliceSpaceTravelling Slice
 *
 * - **API ID**: `default`
 * - **Description**: `SliceSpaceTravelling`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SliceSpaceTravellingSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<SliceSpaceTravellingSliceDefaultPrimary>, never>;
/**
 * Slice variation for *SliceSpaceTravelling*
 *
 */
type SliceSpaceTravellingSliceVariation = SliceSpaceTravellingSliceDefault;
/**
 * SliceSpaceTravelling Shared Slice
 *
 * - **API ID**: `slice_space_travelling`
 * - **Description**: `SliceSpaceTravelling`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SliceSpaceTravellingSlice = prismicT.SharedSlice<"slice_space_travelling", SliceSpaceTravellingSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { PostsDocumentData, PostsDocumentDataGroupItem, PostsDocument, AllDocumentTypes, SliceSpaceTravellingSliceDefaultPrimary, SliceSpaceTravellingSliceDefault, SliceSpaceTravellingSliceVariation, SliceSpaceTravellingSlice };
    }
}
