// Code generated by Slice Machine. DO NOT EDIT.

import SliceSpaceTravelling from './SliceSpaceTravelling';

export {
	SliceSpaceTravelling,
};

export const components = {
	slice_space_travelling: SliceSpaceTravelling,
};
